### ISSUE TITLE
Rainforest Mob Spawns & Neapolitan Features Not Generating

### ISSUE THREAD

**Issue by ChimIsTrash** [team-abnormals/atmospheric#176]
I'm on the latest version of Forge on 1.19.2, with Blueprint 6.1.1, Environmental 3.0.0, Neapolitan 4.0.2, and Atmospheric 5.0.0 without any other mods or datapacks installed.

Only parrots and wolves seem to be spawning in rainforest biomes.
![image](https://user-images.githubusercontent.com/86890911/224462741-271b7514-3d91-4faa-8c72-e11fdae7b4c8.png)
I'm assuming that wolves spawning in rainforest biomes is not intended.
![image](https://user-images.githubusercontent.com/86890911/224462738-7d67abb1-e943-47a8-909d-6fa533fc2c38.png)
No fish in any rainforest waters either.
![image](https://user-images.githubusercontent.com/86890911/224462968-7efb1987-6583-4d7a-acbe-0c814391d334.png)

Chimps and banana trees are supposed to spawn in rainforests when Neapolitan is installed, but they don't. However, I thought I saw a banana tree in a rainforest, but it I think it was a small jungle biome surrounded by rainforests.

They spawn in vanilla jungle biomes just fine.
![image](https://user-images.githubusercontent.com/86890911/224463239-c6927919-cb3e-4489-8648-c6bcfdae5ff5.png)

**Comment by bageldotjpg** [comment]
* Parrots & Wolves in Rainforest are intentional
* Farm animals aren't spawning due to an Environmental feature that limits Pigs & Chickens to forest biomes and Sheep & Cows to plains biomes.
* No fish spawning is also intentional, eventually a special fish type will be added
* No Chimpanzees is due to a Neapolitan bug
