### ISSUE TITLE
lack of biome diversity

### ISSUE THREAD

**Issue by epicmoth** [team-abnormals/atmospheric#195]
whenever i install atmospheric, most of the biomes in the world generated are savannahs and the rainforest biome, i really like this mod but it drives me mad when i find myself in yet another rainforest so ive had to uninstall it.

**Comment by SmellyModder** [comment]
Most of the Rainforest biomes only generate in the same areas where Jungles would generate. If you see a lot of rainforests, you would see mostly jungles instead if the mod wasn't loaded. Additionally, Rainforest biomes are rarer than Jungles. As for Savannas, we do not make them more common because we do not modify biomes in those ranges.

What is happening is you are just getting unlucky. If you want to avoid seeing many Rainforests and Savannas, look for vanilla seeds with few Jungles and Savannas.
